/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista;

import ec.edu.ister.controlador.Coordinador;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author PC6-LAB1
 */

public class Inicio extends javax.swing.JPanel {

    Coordinador coordinador;
    /**
     * Creates new form Inicio
     */
    public Inicio(Coordinador coord) {
        coordinador=coord;
        
        initComponents();
        ImageIcon imagen8 = new ImageIcon("LogoSinFonfoRumi.png");
        Icon icono8 = new ImageIcon(imagen8.getImage().getScaledInstance(390, 320, Image.SCALE_DEFAULT));
        lblLogo1.setIcon(icono8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 45)); // NOI18N
        jLabel1.setText("INSTITUTO TECNOLÓGICO SUPERIOR RUMIÑAHUI");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Sistema de Gestión Académico Docente");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        lblLogo1.setText("Logo");
        add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        lblReloj.setText("Reloj");
        add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, -1));

        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables
}
